### ISSUE TITLE
Line 84 - DCP coming as null if no template is specified during Query

### ISSUE THREAD

**Issue by kpmrafeeq** [dd4t/DD4T.Providers.SDLWeb8#4]
Having issue with below line on the file (https://github.com/dd4t/DD4T.Providers.SDLWeb8/blob/develop/source/DD4T.Providers.SDLWeb8/TridionComponentPresentationProvider.cs)

When the data is compressed, _cp.Content will never have "Component" , so it always returning null
      foreach (Tridion.ContentDelivery.DynamicContent.ComponentPresentation _cp in cps)
            {
                if (_cp != null)
                {
                    if (_cp.Content.Contains("<Component"))
                    {
                        LoggerService.Debug("<<GetContent({0}) - find all", LoggingCategory.Performance, uri);
                        return _cp.Content;
                    }
                }
            }

Expected, we do not need to loop, we can just return as below

if (cp != null)
            {
                return cp.Content;
            }

**Comment by quirijnslings** [comment]
Release 2.5
